export const categoriasPadrao = [
    "Tecnologia",
    "Educação",
    "Ciências",
    "Artes",
    "Saúde",
    "Negócios",
    "Esportes",
    "Entretenimento",
    "Meio Ambiente",
    "Política",
    "História",
    "Filosofia",
    "Psicologia",
    "Direito",
    "Religião",
    "Literatura",
    "Música",
    "Cinema",
    "Culinária",
    "Moda",
    "Design",
    "Fotografia",
    "Viagens",
    "Jogos",
    "Finanças Pessoais",
    "Marketing Digital",
    "Desenvolvimento Pessoal",
    "Inteligência Artificial",
    "Astronomia",
    "Sociologia",
    "Engenharia",
    "Matemática",
    "Física",
    "Química",
    "Biologia",
    "Arquitetura",
    "Animação",
    "Segurança da Informação",
    "Desenvolvimento Web",
    "Mobile",
    "UX/UI",
    "E-commerce",
    "Criptomoedas",
    "Realidade Virtual",
    "Realidade Aumentada",
    "Startups",
    "Empreendedorismo",
    "Carreira e Emprego",
    "Idiomas"
  ];